config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  root 'tops#index'

  devise_for :users
  resources :users, only: :show
  resources :blogs do
    resources :comments, controller: 'blogs/comments'
    resources :favorites, controller: 'blogs/favorites', only: %i[create destroy]
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_rich_text :content

  belongs_to :user

  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true

  belongs_to :blog
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  validates :user_id, uniqueness: { scope: :blog_id }

  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :blogs, dependent: :destroy
  has_many :favorites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/blogs/comments_controller.rb
class Blogs::CommentsController < ApplicationController
  before_action :set_blog, only: [:create, :edit, :update]

  def create
    @comment = @blog.comments.build(comment_params)

    respond_to do |format|
      if @comment.save
        format.js { render :index }
      else
        format.html { redirect_to blog_path(@blog), notice: '投稿エラー' }
      end
    end
  end

  def edit
    @comment = @blog.comments.find(params[:id])
    respond_to do |format|
      flash.now[:notice] = 'コメントの編集中'
      format.js { render :edit }
    end
  end

  def update
    @comment = @blog.comments.find(params[:id])

    respond_to do |format|
      if @comment.update(comment_params)
        flash.now[:notice] = 'コメントが編集されました'
        format.js { render :index }
      else
        flash.now[:notice] = 'コメントの編集に失敗しました'
        format.js { render :edit_error }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      flash.now[:notice] = 'コメントが削除されました'
      format.js { render :index }
    end
  end

  private

  def set_blog
    @blog = Blog.find(params[:blog_id])
  end

  def comment_params
    params.require(:comment).permit(:blog_id, :content)
  end
end

app/controllers/blogs/favorites_controller.rb
class Blogs::FavoritesController < ApplicationController

  def create
    @blog = Blog.find(params[:blog_id])
    Favorite.create(user_id: current_user.id, blog_id: @blog.id)
    redirect_to blog_path(@blog), notice: 'お気に入り追加！'
  end

  def destroy
    @blog = Blog.find(params[:blog_id])
    @favorite = Favorite.find_by(user_id: current_user.id, blog_id: @blog.id)
    if @favorite.destroy
      redirect_to blog_path(@blog), notice: 'お気に入り削除！'
    else
      redirect_to blogs_path, notice: 'お気に入り削除できませんでした。お手数ですが、管理者へ問い合わせて下さい。'
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[show edit update destroy]
  before_action :authenticate_user!

  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = current_user.blogs.build(blog_params)

    if @blog.save
      redirect_to blogs_path, notice: 'ブログを投稿しました'
    else
      render :new
    end
  end

  def show
    @blog = Blog.find(params[:id])
    @comment = @blog.comments.build
    @comments = @blog.comments
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])

    if @blog.update
      redirect_to blogs_path, notice: 'ブログを編集しました'
    else
      rendre :edit
    end
  end

  def destroy
    @blog = Blog.find(params[:id])

    if @blog.destroy
      redirect_to blogs_path, notice: '削除しました'
    else
      render :index
    end
  end

  private

  def set_blog
    @blog = Blog.find(params[:id])
  end

  def blog_params
    params.require(:blog).permit(:title, :content)
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blogs/_form.html.erb
<%= form_with model: blog, local: true do |form| %>
  <div id="error_explanation">
    <% if blog.errors.any? %>
      <p><%= pluralize(blog.errors.count, "error") %></p>
      <ul>
        <% blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
  </div>
    <% end %>

<%= form.label :title %>
<%= form.text_field :title %>

<br>

<%= form.label :content %>
<%= form.rich_text_area :content %>

<%= form.submit '投稿', class: 'btn btn-success' %>
<% end %>

app/views/blogs/comments/_edit.html.erb
<%= form_with model: [blog, comment], local: false do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
        <% comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.text_area :content, id: "comment_content_#{blog.id}" %>
    <%= form.label :content %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/comments/_form.html.erb
<%= form_with model: [blog, comment], local: false do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
        <% comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/comments/_index.html.erb
<ul>
  <% comments.each do |comment| %>
    <% if comment.id.present? %>
      <li>
        <div class="comment-content" id ="this_comment_<%= comment.id %>"></div>
        <p><%= comment.content %></p>
        <p><%= link_to "コメント編集", edit_blog_comment_path(blog, comment), remote: true %></p>
        <p><%= link_to "コメント削除", blog_comment_path(comment.blog_id, comment.id), method: :delete, remote: true,
                                        data: { confirm: "本当に削除しますか?"} %></p>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/blogs/comments/edit.js.erb
$("#this_comment_<%= @comment.id %>").replaceWith("<%= j render 'blogs/comments/edit', blog: @blog, comment: @comment %>");
$("#notice").html("<%= j flash[:notice] %>");

app/views/blogs/comments/index.js.erb
$("#comments_area").html("<%= j(render 'blogs/comments/index', { comments: @comment.blog.comments, blog: @comment.blog } ) %>");
$("textarea").val('');
$("#notice").html("<%= j flash[:notice] %>");

app/views/blogs/edit.html.erb
<h1>ブログ編集</h1>

<%= render 'form', blog: @blog %>

<hr>
<%= link_to '一覧画面へ戻る', blogs_path, class: 'btn btn-secondary' %>

app/views/blogs/index.html.erb
<h1>みんなのブログ一覧</h1>
<%= link_to 'ブログを投稿する', new_blog_path, class: 'btn btn-info' %>

<hr>

<table class="table">
  <tr>
    <th>Coffee Info</th>
  </tr>
  <% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.title %></td>
    <td><%= blog.content %></td>
    <td><%= link_to '詳細', blog_path(blog) %></td>
    <td><%= link_to '編集', edit_blog_path(blog) %></td>
    <td><%= link_to '削除', blog_path(blog), method: :delete, data: { confirm: '削除しますか？' } %></td>
  </tr>
  <% end %>
</table>

app/views/blogs/new.html.erb
<h1>ブログ新規投稿</h1>

<%= render 'form', blog: @blog %>

<hr>
<%= link_to '一覧画面へ戻る', blogs_path, class: 'btn btn-defalt' %>

app/views/blogs/show.html.erb
<h1>ブログ詳細</h1>

<%= @blog.title %>
<%= @blog.content %>

<hr>

<p>コメント一覧</p>

<div id="comments_area">
  <%= render partial: 'blogs/comments/index', locals: { comments: @comments, blog: @blog } %>
</div>

<%= render partial: 'blogs/comments/form', locals: { comment: @comment, blog: @blog } %>

<hr>

<% if Favorite.find_by(user_id: current_user.id, blog_id: @blog.id) %>
  <%= link_to 'お気に入り削除', blog_favorite_path(@blog), method: :delete %>
<% else %>
  <%= link_to 'お気に入り追加', blog_favorites_path(@blog), method: :post %>
<% end %>

<%= link_to '一覧画面へ戻る', blogs_path, class: 'btn btn-secondary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Study</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <% unless controller.controller_name == "tops" %>
    <%= render 'shared/layout/header' %>

    <div class="container">
      <div class="alert-space">
        <% if notice %>
          <p class="alert alert-info"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>
      </div>
      <%= yield %>
    </div>

  <% else %>

    <%= yield %>

  <% end %>

  </body>
</html>

app/views/shared/layout/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand fw-bold" href="/">Coffee Time</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%# <a class="nav-link active" aria-current="page" href="#">リンク</a> %>
        </li>
        <li class="nav-item">
          <%# <a class="nav-link" href="#">リンク２</a> %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-black" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            MENU
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% if user_signed_in? %>
              <li><%= link_to "マイページ", user_path(current_user), class: 'dropdown-item' %></li>
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'dropdown-item' %></li>
            <% else %>
              <li><%= link_to "新規登録", new_user_registration_path, class: 'dropdown-item' %></li>
              <li><%= link_to "ログイン", new_user_session_path, class: 'dropdown-item' %></li>
            <% end %>
            <%# <li><hr class="dropdown-divider"></li> %>
            <%# <li><a class="dropdown-item" href="#">リンク５</a></li> %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/tops/index.html.erb
<div class="position-relative top-title-box">
  <h1 class="position-absolute top-title">Coffe Time</h1>
  <p class="position-absolute top-title-content" >新たなコーヒーと出逢いましょう！</p>
  <%= link_to "新規登録", new_user_registration_path, class: 'position-absolute sign-up-link top-button' %>
  <%= link_to "ログイン", new_user_session_path, class: 'position-absolute sign-in-link top-button' %>
  <%= image_pack_tag 'top.jpg', class: 'top-title-image' %>
</div>
<div class="row row-cols-1 row-cols-md-3 g-4 mt-5">
  <div class="col">
    <div class="card h-100">
      <%= image_pack_tag 'top-image1.jpg', class: 'card-img-top' %>
      <div class="card-body text-center">
        <h5 class="card-title">同じ趣味を持つ集まり</h5>
        <p class="card-text">お気に入りのコーヒー情報を投稿しましょう</p>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card h-100">
      <%= image_pack_tag 'top-image2.jpg', class: 'card-img-top' %>
      <div class="card-body text-center">
        <h5 class="card-title">気になる情報をチェック</h5>
        <p class="card-text">いいね機能やフォロー機能で気になっていた情報へ素早くアクセス</p>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card h-100">
      <%= image_pack_tag 'top-image3.jpg', class: 'card-img-top' %>
      <div class="card-body text-center">
        <h5 class="card-title">交流</h5>
        <p class="card-text">気になることはメッセージで聞いてみましょう</p>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1>マイページ</h1>

<h3>メールアドレス</h3>
<%= @user.email %>

<hr>

<h3>お気に入り記事一覧</h3>
<ul>
  <% @user.favorites.each do |favorite| %>
    <li><%= link_to favorite.blog.title, blog_path(favorite.blog.id) %></li>
  <% end %>
</ul>

<hr>

<%= link_to 'ブログ一覧へ', blogs_path %>